project:
  type: website
  preview:
    port: 4321

website:
  title: "RevealJS Theme"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Top Level Presentation
        href: presentation.qmd
      - text: Nested Presentation
        href: examples/presentation.qmd

format: custom-html

