project:
  type: website
  preview:
    port: 4321

website:
  title: "Failing RevealJS SCSS Discovery"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.qmd

format: custom-html
